theme = 'ananke'

[security]
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^pandoc$']



[params]
  description = 'books'
  [params.brand]
    name = 'The Witcher'
    author = 'Sapkowski Andrzej'
    path = '/images/2.jpg'


[markup.goldmark.renderer]
unsafe = true
